name: Build, test, release

on:
  # note "create" event is just so our flows trigger on tag pushes that
  # are tagged with [ci skip], see https://github.com/orgs/community/discussions/179637
  create:
  workflow_dispatch:  # allows manually triggered workflows
  push:

jobs:
  call-build:
    uses: haridusministeerium/workflows/.github/workflows/docker-build-publish.yml@master
    secrets: inherit
    with:
      image: layr/docker-gh-actions-reuse-test

